# -*- coding: utf-8 -*-
"""images_path and labels for tumor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GKmqzuLjxxwsgLbB1L8GIRyfs0tBvkFM
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd

train='/content/drive// My Drive/CNN folder/Tumor/tumor/Training/'
test='/content/drive// My Drive/CNN folder/Tumor/tumor/Testing/'

train_df = pd.DataFrame()
test_df=pd.DataFrame()



training_files=os.listdir(train)
test_files=os.listdir(test)

print(training_files)

image_paths = []
image_labels = []

for i in range(len(training_files)):
  classes= ["glioma_tumor", "meningioma_tumor", "no_tumor", "pituitary_tumor"]

  folder_path=train + training_files[i]

  files_folders=os.listdir(folder_path)

  for img in range(len(files_folders)):
    image_path=folder_path + '/'  +files_folders[img]
    image_label=classes[i]

    image_paths.append(image_path)
    image_labels.append(image_label)
 # Verify the lengths before assignment
print(len(image_paths))
print(len(image_labels))
train_df['image_path'] = image_paths
train_df['label'] = image_labels

train_df['image_path'][0]

# Map the 'label' column using the defined mapping
class_mapping = {"glioma_tumor": 0, "meningioma_tumor": 1, "no_tumor": 2, "pituitary_tumor": 3}

train_df['label'] = train_df['label'].map(class_mapping)

test_images_paths=[]
test_images_labels=[]

for i in range(len(test_files)):
  folder_path2=test+test_files[i]
  files_folders2=os.listdir(folder_path2)
  for img in range(len(files_folders2)):
    image_path2=folder_path2 + '/'  +files_folders2[img]
    image_label2=classes[i]

    test_images_paths.append(image_path2)
    test_images_labels.append(image_label2)
 # Verify the lengths before assignment
print(len(image_paths))
print(len(image_labels))
test_df['image_path'] = test_images_paths
test_df['label'] = test_images_labels

print(len(test_images_paths))
print(len(test_images_labels))

# Map the 'label' column using the defined mapping
class_mapping = {"glioma_tumor": 0, "meningioma_tumor": 1, "no_tumor": 2, "pituitary_tumor": 3}

test_df['label'] = test_df['label'].map(class_mapping)

train_df.info()

test_df.info()

# Assuming train_df is your DataFrame
train_df.to_csv('/content/drive// My Drive/CNN folder/Tumor/tumor/training_data.csv', index=False)
test_df.to_csv('/content/drive// My Drive/CNN folder/Tumor/tumor/testing_data.csv', index=False)

test_df["image_path"][0]